"""added pfp_public_id attribute to user model

Revision ID: 1c83fbf21fdd
Revises: 26c40badc00c
Create Date: 2025-09-17 16:50:52.419733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c83fbf21fdd'
down_revision: Union[str, Sequence[str], None] = '26c40badc00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pfp_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pfp_public_id')
    # ### end Alembic commands ###
