"""added pfp attribute to the user model

Revision ID: 26c40badc00c
Revises: 76d5a199d507
Create Date: 2025-09-17 12:31:49.821666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c40badc00c'
down_revision: Union[str, Sequence[str], None] = '76d5a199d507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pfp', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pfp')
    # ### end Alembic commands ###
