"""added post attachments

Revision ID: 46d1cce4a65c
Revises: 1c83fbf21fdd
Create Date: 2025-09-17 22:43:25.653489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d1cce4a65c'
down_revision: Union[str, Sequence[str], None] = '1c83fbf21fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.Text(), nullable=False),
    sa.Column('file_public_id', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_attachments_id'), 'post_attachments', ['id'], unique=False)
    op.add_column('dm_messages', sa.Column('attachment', sa.String(length=255), nullable=True))
    op.add_column('dm_messages', sa.Column('attachment_public_id', sa.String(length=255), nullable=True))
    # Keep the original constraint name - no need to change it
    # op.drop_constraint(op.f('unique_follow_request'), 'follow_requests', type_='unique')
    # op.create_unique_constraint('unique_follow_request', 'follow_requests', ['from_user_id', 'to_user_id'])
    op.add_column('group_chat_messages', sa.Column('attachment', sa.String(length=255), nullable=True))
    op.add_column('group_chat_messages', sa.Column('attachment_public_id', sa.String(length=255), nullable=True))
    op.add_column('room_messages', sa.Column('attachment', sa.String(length=255), nullable=True))
    op.add_column('room_messages', sa.Column('attachment_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_messages', 'attachment_public_id')
    op.drop_column('room_messages', 'attachment')
    op.drop_column('group_chat_messages', 'attachment_public_id')
    op.drop_column('group_chat_messages', 'attachment')
    # Keep the original constraint name - no need to change it
    # op.drop_constraint('unique_follow_request', 'follow_requests', type_='unique')
    # op.create_unique_constraint(op.f('unique_follow_request'), 'follow_requests', ['from_user_id', 'to_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('dm_messages', 'attachment_public_id')
    op.drop_column('dm_messages', 'attachment')
    op.drop_index(op.f('ix_post_attachments_id'), table_name='post_attachments')
    op.drop_table('post_attachments')
    # ### end Alembic commands ###
