"""added post attachments

Revision ID: 9b0ee81dd707
Revises: 46d1cce4a65c
Create Date: 2025-09-17 22:51:13.418601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b0ee81dd707'
down_revision: Union[str, Sequence[str], None] = '46d1cce4a65c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_follow'), 'follows', type_='unique')
    op.create_unique_constraint('unique_follow_relationship', 'follows', ['follower_id', 'followed_id'])
    op.add_column('users', sa.Column('pfp_public_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pfp_public_id')
    op.drop_constraint('unique_follow_relationship', 'follows', type_='unique')
    op.create_unique_constraint(op.f('unique_follow'), 'follows', ['follower_id', 'followed_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
